esphome:
    name: wetterstation
  
  esp8266:
    board: d1_mini
  
  # Enable logging
  logger:
  
  # Enable Home Assistant API
  api:
    password: "" # muss angepasst werden
  ota:
    password: "" # muss angepasst werden
  
  wifi:
    ssid: !secret wifi_ssid # muss angepasst werden
    password: !secret wifi_password # muss angepasst werden
  
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: "Wetterstation Fallback Hotspot"
      password: "" # muss angepasst werden
  
  captive_portal:
      
  dallas:
    - pin: D2
      update_interval: 300s
  
  # Individual sensors
  sensor:
    - platform: dallas
      address: 0x050119396EA1B128 # muss angepasst werden
      name: "outdoortemp2"
  
      
    - platform: pulse_counter
      name: "rain_gauge"
      update_interval: 120s
      pin:
        number: D5
        mode: INPUT_PULLUP    
      count_mode:
        rising_edge: DISABLE
        falling_edge: INCREMENT
      internal_filter: 10ms
      unit_of_measurement: "mm"
      icon: "mdi:water"
      filters:
        - multiply: 0.359254458